[general]
import = [
  "~/.config/alacritty/themes/catppuccin_frappe.toml"
]

[window]
dynamic_title = true
padding = { x = 5, y = 5 }
dimensions = { columns = 160, lines = 50 }

[font]
normal = { family = "BitstromWera Nerd Font Mono", style = "Regular" }
bold = { family = "BitstromWera Nerd Font Mono", style = "Bold" }
size = 11.5
offset = { x = 1, y = 1 }

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 678
